//
//  Product.swift
//  OnlineGroceriet
//
//  Created by Engy on 12/1/24.
//

import Foundation
struct DummyProduct {
    let id: Int
    let name: String
    let price: Double
    let quantity: String
    let imageName: String
    let category: String
    let brand: String
    let nutritionsPerAmount: String
    let nutritionsDetail: String
    let productDetail: String
    let review: String
}
let dummyProducts: [DummyProduct] = [
    // Beverages
    DummyProduct(id: 1, name: "Diet Coke", price: 1.99, quantity: "355ml", imageName: "DietCoke", category: "Beverages", brand: "Coca Cola", nutritionsPerAmount: "100ml", nutritionsDetail: "0 kcal, 0g fat, 0g sugar, 0g protein", productDetail: "Diet Coke is a zero-calorie, sugar-free soft drink. It offers the refreshing taste of Coca-Cola with no sugar or calories. Ideal for those seeking a calorie-conscious beverage. Perfectly carbonated for a crisp, bubbly experience.", review: "4.2"),
    DummyProduct(id: 2, name: "Sprite Can", price: 1.50, quantity: "325ml", imageName: "SpriteCan", category: "Beverages", brand: "Coca Cola", nutritionsPerAmount: "100ml", nutritionsDetail: "39 kcal, 0g fat, 9g sugar, 0g protein", productDetail: "Sprite is a refreshing lemon-lime soda with a crisp, clean taste. It's perfect for quenching your thirst on a hot day. Made with natural flavors and no caffeine. A great mixer for your favorite cocktails or enjoyed on its own.", review: "3.9"),
    DummyProduct(id: 3, name: "Apple & Grape Juice", price: 15.99, quantity: "2L", imageName: "Apple&GrapeJuice", category: "Beverages", brand: "FruitCo", nutritionsPerAmount: "100ml", nutritionsDetail: "45 kcal, 0g fat, 11g sugar, 0.1g protein", productDetail: "A delicious blend of apple and grape juices. Packed with natural flavors and antioxidants. This juice is 100% pure fruit with no added preservatives. Ideal for a morning boost or a refreshing snack any time of the day.", review: "4.5"),
    DummyProduct(id: 4, name: "Orange Juice", price: 15.99, quantity: "2L", imageName: "OrangeJuice", category: "Beverages", brand: "CitrusFresh", nutritionsPerAmount: "100ml", nutritionsDetail: "50 kcal, 0g fat, 12g sugar, 1g protein", productDetail: "Freshly squeezed orange juice that brings the sunny taste of ripe oranges to your glass. Packed with vitamin C, this juice supports your immune system. No added sugar or artificial flavors. Perfect for breakfast or a healthy snack.", review: "4.7"),
    DummyProduct(id: 5, name: "Coca Cola Can", price: 4.99, quantity: "325ml", imageName: "CocaColaCan", category: "Beverages", brand: "Coca Cola", nutritionsPerAmount: "100ml", nutritionsDetail: "42 kcal, 0g fat, 10.6g sugar, 0g protein", productDetail: "Coca-Cola, a classic soda, loved worldwide for its signature taste. Perfectly balanced with sweetness and fizziness. This refreshing drink pairs well with any meal or can be enjoyed as a standalone treat. Available in a convenient can size.", review: "4.0"),
    DummyProduct(id: 6, name: "Iced Tea", price: 2.49, quantity: "500ml", imageName: "icedtea", category: "Beverages", brand: "TeaCo", nutritionsPerAmount: "100ml", nutritionsDetail: "20 kcal, 0g fat, 5g sugar, 0g protein", productDetail: "Sweetened iced tea for a refreshing drink. Made from high-quality tea leaves with a smooth and balanced flavor. Low in calories and caffeine-free, it is a perfect drink for any occasion. Best served chilled for ultimate refreshment.", review: "4.3"),

    // Fruits
    DummyProduct(id: 7, name: "Organic Bananas", price: 4.99, quantity: "7pcs", imageName: "OrganicBananas", category: "Fruits", brand: "FreshFruits", nutritionsPerAmount: "100g", nutritionsDetail: "89 kcal, 0.3g fat, 23g carbs, 1.1g protein", productDetail: "Natural source of potassium and fiber, these organic bananas are rich in nutrients. They are grown without pesticides or chemicals, ensuring a wholesome fruit experience. Great for a quick snack or in smoothies and desserts.", review: "4.6"),
    DummyProduct(id: 8, name: "Red Apple", price: 4.99, quantity: "1kg", imageName: "RedApple", category: "Fruits", brand: "OrchardFresh", nutritionsPerAmount: "100g", nutritionsDetail: "52 kcal, 0.2g fat, 14g carbs, 0.3g protein", productDetail: "Nutritious and sweet apples grown in orchards with optimal care. These apples are a perfect balance of sweetness and tartness. Rich in fiber and antioxidants, they promote digestive health. Ideal for snacking or adding to salads.", review: "4.3"),
    DummyProduct(id: 9, name: "Green Grapes", price: 3.99, quantity: "500g", imageName: "GreenGrapes", category: "Fruits", brand: "GrapeCo", nutritionsPerAmount: "100g", nutritionsDetail: "69 kcal, 0.2g fat, 18g carbs, 0.6g protein", productDetail: "Juicy and sweet green grapes, full of natural sugars and antioxidants. These grapes are perfect for snacking or as an addition to fruit salads. Their refreshing taste makes them ideal for hot summer days. Enjoy them fresh or frozen.", review: "4.1"),
    DummyProduct(id: 10, name: "Watermelon", price: 6.99, quantity: "1pc", imageName: "Watermelon", category: "Fruits", brand: "FreshFruits", nutritionsPerAmount: "100g", nutritionsDetail: "30 kcal, 0.2g fat, 8g carbs, 0.6g protein", productDetail: "Hydrating and refreshing watermelon, perfect for hot days. Packed with water content to keep you hydrated. Sweet and juicy with a perfect balance of flavors, this fruit is great on its own or in fruit salads.", review: "4.8"),
    DummyProduct(id: 11, name: "Pineapple", price: 5.49, quantity: "1pc", imageName: "pineapple", category: "Fruits", brand: "TropicalDelights", nutritionsPerAmount: "100g", nutritionsDetail: "50 kcal, 0.1g fat, 13g carbs, 0.5g protein", productDetail: "Tropical and sweet pineapple, perfect for eating fresh or in smoothies. Known for its rich vitamin C content, it helps boost immunity and digestion. This pineapple is handpicked for the sweetest taste and juiciness.", review: "4.7"),
    DummyProduct(id: 12, name: "Mangoes", price: 7.99, quantity: "2pcs", imageName: "mango", category: "Fruits", brand: "TropicalDelights", nutritionsPerAmount: "100g", nutritionsDetail: "60 kcal, 0.2g fat, 15g carbs, 0.8g protein", productDetail: "Sweet and juicy mangoes with rich tropical flavor. These mangoes are the perfect balance of tartness and sweetness. Great for snacking or adding to smoothies, salads, and desserts. Full of vitamins and antioxidants.", review: "4.9"),

    // Vegetables
    DummyProduct(id: 13, name: "Carrots", price: 2.99, quantity: "500g", imageName: "carrot", category: "Vegetables", brand: "FreshVeg", nutritionsPerAmount: "100g", nutritionsDetail: "41 kcal, 0.2g fat, 10g carbs, 0.9g protein", productDetail: "Fresh and crunchy carrots.", review: "4.5"),
    DummyProduct(id: 14, name: "Spinach", price: 3.49, quantity: "500g", imageName: "spinach", category: "Vegetables", brand: "GreenFarm", nutritionsPerAmount: "100g", nutritionsDetail: "23 kcal, 0.4g fat, 4g carbs, 2.9g protein", productDetail: "Rich in vitamins and minerals.", review: "4.7"),
    DummyProduct(id: 15, name: "Cucumber", price: 2.19, quantity: "3pcs", imageName: "cucumber", category: "Vegetables", brand: "GreenFarm", nutritionsPerAmount: "100g", nutritionsDetail: "16 kcal, 0.1g fat, 4g carbs, 0.7g protein", productDetail: "Refreshing and hydrating cucumbers.", review: "4.2"),
    DummyProduct(id: 16, name: "Potatoes", price: 4.99, quantity: "1kg", imageName: "potato", category: "Vegetables", brand: "FarmFresh", nutritionsPerAmount: "100g", nutritionsDetail: "77 kcal, 0.1g fat, 17g carbs, 2g protein", productDetail: "Staple and versatile vegetable.", review: "4.5"),
    DummyProduct(id: 17, name: "Broccoli", price: 3.99, quantity: "500g", imageName: "broccoli", category: "Vegetables", brand: "GreenFarm", nutritionsPerAmount: "100g", nutritionsDetail: "34 kcal, 0.4g fat, 7g carbs, 3g protein", productDetail: "High in fiber and vitamins.", review: "4.6"),
    DummyProduct(id: 18, name: "Lettuce", price: 2.50, quantity: "1head", imageName: "lettuce", category: "Vegetables", brand: "FreshVeg", nutritionsPerAmount: "100g", nutritionsDetail: "15 kcal, 0.2g fat, 3g carbs, 1g protein", productDetail: "Crisp and fresh lettuce.", review: "4.4"),
    DummyProduct(id: 19, name: "Cauliflower", price: 3.89, quantity: "500g", imageName: "cauliflower", category: "Vegetables", brand: "FarmFresh", nutritionsPerAmount: "100g", nutritionsDetail: "25 kcal, 0.3g fat, 5g carbs, 2g protein", productDetail: "Low-carb and versatile vegetable.", review: "4.6"),
    DummyProduct(id: 20, name: "Tomatoes", price: 3.49, quantity: "500g", imageName: "tomato", category: "Vegetables", brand: "FreshVeg", nutritionsPerAmount: "100g", nutritionsDetail: "18 kcal, 0.2g fat, 4g carbs, 0.9g protein", productDetail: "Fresh and juicy tomatoes.", review: "4.3"),
    DummyProduct(id: 21, name: "Onions", price: 2.99, quantity: "1kg", imageName: "onion", category: "Vegetables", brand: "FarmFresh", nutritionsPerAmount: "100g", nutritionsDetail: "40 kcal, 0.1g fat, 9g carbs, 1g protein", productDetail: "Versatile and flavorful onions.", review: "4.4"),
    DummyProduct(id: 22, name: "Bell Peppers", price: 5.99, quantity: "500g", imageName: "bellpepper", category: "Vegetables", brand: "GreenFarm", nutritionsPerAmount: "100g", nutritionsDetail: "20 kcal, 0.2g fat, 5g carbs, 1g protein", productDetail: "Sweet and crunchy bell peppers.", review: "4.6"),

    // Dairy
    DummyProduct(id: 23, name: "Milk", price: 1.50, quantity: "1L", imageName: "milk", category: "Dairy", brand: "DairyBest", nutritionsPerAmount: "100ml", nutritionsDetail: "42 kcal, 1g fat, 5g carbs, 3g protein", productDetail: "Fresh milk from local farms, ideal for drinking, baking, or cooking. Rich in calcium and essential vitamins, providing a nutritious option for your daily needs.", review: "4.7"),
    DummyProduct(id: 24, name: "Cheddar Cheese", price: 5.00, quantity: "200g", imageName: "cheddar", category: "Dairy", brand: "CheeseCo", nutritionsPerAmount: "100g", nutritionsDetail: "402 kcal, 33g fat, 1g carbs, 25g protein", productDetail: "Sharp and tangy cheddar cheese, perfect for sandwiches, crackers, or melting into a savory dish. Made from the finest milk, aged to develop a rich, bold flavor.", review: "4.4"),
    DummyProduct(id: 25, name: "Yogurt", price: 2.00, quantity: "500g", imageName: "yogurt", category: "Dairy", brand: "YogurtCo", nutritionsPerAmount: "100g", nutritionsDetail: "61 kcal, 3g fat, 7g carbs, 4g protein", productDetail: "Creamy yogurt made with live cultures, promoting gut health and digestion. A delicious snack or breakfast option, available in various flavors.", review: "4.6"),
    DummyProduct(id: 26, name: "Butter", price: 3.50, quantity: "250g", imageName: "butter", category: "Dairy", brand: "ButterCo", nutritionsPerAmount: "100g", nutritionsDetail: "717 kcal, 81g fat, 1g carbs, 1g protein", productDetail: "Rich and creamy butter, perfect for spreading on bread or using in cooking and baking. Made from high-quality cream, it adds a rich taste to your dishes.", review: "4.8"),
    DummyProduct(id: 27, name: "Cream Cheese", price: 4.50, quantity: "200g", imageName: "creamcheese", category: "Dairy", brand: "CheeseCo", nutritionsPerAmount: "100g", nutritionsDetail: "342 kcal, 33g fat, 2g carbs, 6g protein", productDetail: "Smooth and tangy cream cheese, ideal for bagels, spreading on toast, or as a dip base. Made from fresh cream and milk for a velvety texture and rich taste.", review: "4.5"),
    DummyProduct(id: 28, name: "Ricotta Cheese", price: 5.99, quantity: "250g", imageName: "ricotta", category: "Dairy", brand: "CheeseCo", nutritionsPerAmount: "100g", nutritionsDetail: "174 kcal, 14g fat, 3g carbs, 11g protein", productDetail: "Creamy and mild ricotta cheese, perfect for making lasagna, stuffed pastas, or desserts. Made from fresh whey for a smooth, soft texture.", review: "4.6"),

    // Snacks
    DummyProduct(id: 29, name: "Potato Chips", price: 1.99, quantity: "150g", imageName: "chips", category: "Snacks", brand: "SnackCo", nutritionsPerAmount: "100g", nutritionsDetail: "536 kcal, 33g fat, 53g carbs, 7g protein", productDetail: "Crispy and savory potato chips, perfect for snacking. Lightly salted and cooked to a golden crisp for a satisfying crunch with every bite.", review: "4.2"),
    DummyProduct(id: 30, name: "Chocolate Bar", price: 2.50, quantity: "100g", imageName: "chocolate", category: "Snacks", brand: "SweetTreat", nutritionsPerAmount: "100g", nutritionsDetail: "535 kcal, 30g fat, 60g carbs, 4g protein", productDetail: "Rich and creamy chocolate, ideal for satisfying your sweet cravings. Made with high-quality cocoa beans and smooth milk for a delicious treat.", review: "4.5"),
    DummyProduct(id: 31, name: "Gummy Bears", price: 1.50, quantity: "200g", imageName: "gummy", category: "Snacks", brand: "SweetCo", nutritionsPerAmount: "100g", nutritionsDetail: "359 kcal, 0g fat, 89g carbs, 5g protein", productDetail: "Sweet and chewy gummy candies, loved by kids and adults alike. A fun snack available in various fruity flavors.", review: "4.0"),
    DummyProduct(id: 32, name: "Granola Bars", price: 3.99, quantity: "250g", imageName: "granola", category: "Snacks", brand: "CrunchCo", nutritionsPerAmount: "100g", nutritionsDetail: "450 kcal, 20g fat, 65g carbs, 6g protein", productDetail: "Healthy and crunchy granola bars, perfect for a quick breakfast or energy boost. Packed with oats, nuts, and honey for a satisfying, wholesome snack.", review: "4.4"),
    DummyProduct(id: 33, name: "Popcorn", price: 2.00, quantity: "200g", imageName: "popcorn", category: "Snacks", brand: "SnackCo", nutritionsPerAmount: "100g", nutritionsDetail: "375 kcal, 10g fat, 65g carbs, 8g protein", productDetail: "Light and fluffy popcorn, perfect for movie nights or snacking. Low in fat and full of fiber for a satisfying treat without the guilt.", review: "4.6"),
    DummyProduct(id: 34, name: "Pretzels", price: 2.99, quantity: "150g", imageName: "pretzel", category: "Snacks", brand: "CrunchCo", nutritionsPerAmount: "100g", nutritionsDetail: "380 kcal, 8g fat, 72g carbs, 8g protein", productDetail: "Salty and crunchy pretzels, great for snacking on-the-go. Perfectly baked with just the right amount of salt for a deliciously satisfying snack.", review: "4.2"),

    // Meat
    DummyProduct(id: 30, name: "Chicken Breast", price: 5.99, quantity: "500g", imageName: "chicken_breast", category: "Meat", brand: "FarmFresh", nutritionsPerAmount: "100g", nutritionsDetail: "165 kcal, 3.6g fat, 0g carbs, 31g protein", productDetail: "Tender chicken breast, perfect for grilling or baking. Low in fat and high in protein, this cut is ideal for a healthy meal.", review: "4.7"),
    DummyProduct(id: 31, name: "Beef Steak", price: 12.99, quantity: "1kg", imageName: "beef_steak", category: "Meat", brand: "PrimeMeat", nutritionsPerAmount: "100g", nutritionsDetail: "250 kcal, 20g fat, 0g carbs, 22g protein", productDetail: "Juicy and tender steak cuts, perfect for grilling or pan-searing. Rich in flavor and marbled for a melt-in-your-mouth texture.", review: "4.8"),
    DummyProduct(id: 32, name: "Pork Chops", price: 7.99, quantity: "500g", imageName: "pork_chops", category: "Meat", brand: "Butcher'sChoice", nutritionsPerAmount: "100g", nutritionsDetail: "242 kcal, 16g fat, 0g carbs, 22g protein", productDetail: "Delicious, succulent pork chops, great for grilling or roasting. Flavorful and tender with just the right amount of fat.", review: "4.5"),
    DummyProduct(id: 33, name: "Ground Turkey", price: 4.50, quantity: "500g", imageName: "ground_turkey", category: "Meat", brand: "FreshPoultry", nutritionsPerAmount: "100g", nutritionsDetail: "120 kcal, 4g fat, 0g carbs, 22g protein", productDetail: "Lean ground turkey, perfect for burgers, tacos, or meatballs. A great lower-fat alternative to beef with a mild flavor.", review: "4.3"),
    DummyProduct(id: 34, name: "Lamb Shanks", price: 9.99, quantity: "500g", imageName: "lamb_shanks", category: "Meat", brand: "GourmetMeats", nutritionsPerAmount: "100g", nutritionsDetail: "250 kcal, 20g fat, 0g carbs, 20g protein", productDetail: "Tender and flavorful lamb shanks, ideal for slow cooking. Rich in taste and perfect for stews or braises.", review: "4.6"),
    DummyProduct(id: 35, name: "Turkey Breast", price: 6.50, quantity: "500g", imageName: "turkey_breast", category: "Meat", brand: "PoultryChoice", nutritionsPerAmount: "100g", nutritionsDetail: "135 kcal, 2g fat, 0g carbs, 29g protein", productDetail: "Low-fat and high-protein turkey breast, ideal for roasting or making sandwiches. A healthy alternative to chicken or beef.", review: "4.5"),
    // Frozen Foods
    DummyProduct(id: 36, name: "Frozen French Fries", price: 3.99, quantity: "1kg", imageName: "french_fries", category: "Frozen Foods", brand: "CrispyDelight", nutritionsPerAmount: "100g", nutritionsDetail: "310 kcal, 15g fat, 35g carbs, 3g protein", productDetail: "Crispy, golden French fries, ready to cook. Perfect for a quick snack or a side dish.", review: "4.4"),
    DummyProduct(id: 37, name: "Frozen Peas", price: 2.49, quantity: "500g", imageName: "frozen_peas", category: "Frozen Foods", brand: "GreenHarvest", nutritionsPerAmount: "100g", nutritionsDetail: "81 kcal, 0.4g fat, 14g carbs, 5g protein", productDetail: "Fresh frozen peas, perfect for adding to soups, stews, or as a healthy side dish.", review: "4.6"),
    DummyProduct(id: 38, name: "Frozen Broccoli", price: 2.99, quantity: "500g", imageName: "frozen_broccoli", category: "Frozen Foods", brand: "VeggieFresh", nutritionsPerAmount: "100g", nutritionsDetail: "34 kcal, 0.4g fat, 7g carbs, 2.8g protein", productDetail: "High-quality frozen broccoli florets, rich in vitamins and perfect for steaming or stir-frying.", review: "4.7"),
    DummyProduct(id: 39, name: "Frozen Pizza", price: 6.99, quantity: "350g", imageName: "frozen_pizza", category: "Frozen Foods", brand: "PizzaWorld", nutritionsPerAmount: "100g", nutritionsDetail: "270 kcal, 10g fat, 30g carbs, 8g protein", productDetail: "Delicious frozen pizza with cheese and toppings. Convenient and tasty for a quick meal.", review: "4.3"),
    DummyProduct(id: 40, name: "Frozen Chicken Nuggets", price: 4.49, quantity: "600g", imageName: "chicken_nuggets", category: "Frozen Foods", brand: "SnackTime", nutritionsPerAmount: "100g", nutritionsDetail: "295 kcal, 17g fat, 19g carbs, 14g protein", productDetail: "Crispy chicken nuggets, easy to cook and perfect for dipping or as a meal for kids and adults.", review: "4.5"),
    DummyProduct(id: 41, name: "Frozen Mixed Vegetables", price: 2.99, quantity: "500g", imageName: "mixed_vegetables", category: "Frozen Foods", brand: "VeggieMix", nutritionsPerAmount: "100g", nutritionsDetail: "45 kcal, 0.4g fat, 9g carbs, 2g protein", productDetail: "A healthy mix of frozen vegetables, ideal for adding to stir-fries, soups, or as a nutritious side dish.", review: "4.6"),
    DummyProduct(id: 42, name: "Frozen Waffles", price: 3.99, quantity: "300g", imageName: "frozen_waffles", category: "Frozen Foods", brand: "WaffleDelights", nutritionsPerAmount: "100g", nutritionsDetail: "270 kcal, 13g fat, 35g carbs, 4g protein", productDetail: "Sweet and crispy frozen waffles, ready to toast and enjoy with syrup, fruit, or toppings of your choice.", review: "4.4"),
    DummyProduct(id: 43, name: "Frozen Garlic Bread", price: 3.50, quantity: "400g", imageName: "garlic_bread", category: "Frozen Foods", brand: "GarlicBites", nutritionsPerAmount: "100g", nutritionsDetail: "280 kcal, 12g fat, 35g carbs, 6g protein", productDetail: "Frozen garlic bread with rich flavor, perfect as a side dish or snack with pasta, soups, or salads.", review: "4.3"),

    // Canned Goods
    DummyProduct(id: 44, name: "Canned Tomatoes", price: 1.99, quantity: "400g", imageName: "canned_tomatoes", category: "Canned Goods", brand: "TomatoBest", nutritionsPerAmount: "100g", nutritionsDetail: "18 kcal, 0.2g fat, 4g carbs, 1g protein", productDetail: "Freshly packed tomatoes in a can, perfect for sauces, soups, or stews. A kitchen essential for many recipes.", review: "4.7"),
    DummyProduct(id: 45, name: "Canned Sweet Corn", price: 2.49, quantity: "300g", imageName: "canned_corn", category: "Canned Goods", brand: "GoldenCorn", nutritionsPerAmount: "100g", nutritionsDetail: "96 kcal, 1.5g fat, 18g carbs, 3g protein", productDetail: "Sweet corn kernels packed in a can, great for adding to salads, casseroles, or enjoying as a side dish.", review: "4.6"),
    DummyProduct(id: 46, name: "Canned Tuna", price: 3.99, quantity: "185g", imageName: "canned_tuna", category: "Canned Goods", brand: "TunaCatch", nutritionsPerAmount: "100g", nutritionsDetail: "132 kcal, 1g fat, 0g carbs, 28g protein", productDetail: "Canned tuna in water, rich in protein and omega-3 fatty acids, perfect for salads, sandwiches, or casseroles.", review: "4.5"),
    DummyProduct(id: 47, name: "Canned Baked Beans", price: 2.79, quantity: "400g", imageName: "canned_beans", category: "Canned Goods", brand: "BeanDelight", nutritionsPerAmount: "100g", nutritionsDetail: "98 kcal, 0.5g fat, 17g carbs, 5g protein", productDetail: "Canned baked beans in rich tomato sauce, a classic side dish or base for many recipes like chili.", review: "4.3"),
    DummyProduct(id: 48, name: "Canned Pineapple", price: 2.19, quantity: "500g", imageName: "canned_pineapple", category: "Canned Goods", brand: "TropicalFruit", nutritionsPerAmount: "100g", nutritionsDetail: "50 kcal, 0.1g fat, 13g carbs, 0.5g protein", productDetail: "Canned pineapple chunks in syrup, perfect for desserts, smoothies, or tropical recipes.", review: "4.4"),
    DummyProduct(id: 49, name: "Canned Peas", price: 1.99, quantity: "400g", imageName: "canned_peas", category: "Canned Goods", brand: "FreshPeas", nutritionsPerAmount: "100g", nutritionsDetail: "81 kcal, 0.4g fat, 14g carbs, 5g protein", productDetail: "Fresh peas packed in a can, ideal for adding to stews, casseroles, or serving as a side dish.", review: "4.6"),
]

